package com.github.misterchangray.dao.mapper;

import com.github.misterchangray.dao.entity.CommonAuthorizeCode;
import com.github.misterchangray.dao.entity.CommonAuthorizeCodeQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonAuthorizeCodeMapper {
    long countByQuery(CommonAuthorizeCodeQuery query);

    int deleteByQuery(CommonAuthorizeCodeQuery query);

    int insert(CommonAuthorizeCode record);

    int insertSelective(CommonAuthorizeCode record);

    List<CommonAuthorizeCode> selectByQuery(CommonAuthorizeCodeQuery query);

    int updateByQuerySelective(@Param("record") CommonAuthorizeCode record, @Param("example") CommonAuthorizeCodeQuery query);

    int updateByQuery(@Param("record") CommonAuthorizeCode record, @Param("example") CommonAuthorizeCodeQuery query);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_authorize_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CommonAuthorizeCode> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_authorize_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CommonAuthorizeCode> list, @Param("selective") CommonAuthorizeCode.Column ... selective);
}