package com.github.misterchangray.dao.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="com.github.misterchangray.dao.entity.CommonAuthorizeCode")
public class CommonAuthorizeCode {
    @ApiModelProperty(value="id")
    private String id;

    @ApiModelProperty(value="name")
    private String name;

    @ApiModelProperty(value="description")
    private String description;

    @ApiModelProperty(value="code")
    private String code;

    @ApiModelProperty(value="enabled0false;1true")
    private Integer enabled;

    @ApiModelProperty(value="deleted0false;1true")
    private Integer deleted;

    public String getId() {
        return id;
    }

    public CommonAuthorizeCode setId(String id) {
        this.id = id == null ? null : id.trim();
        return this;
    }

    public String getName() {
        return name;
    }

    public CommonAuthorizeCode setName(String name) {
        this.name = name == null ? null : name.trim();
        return this;
    }

    public String getDescription() {
        return description;
    }

    public CommonAuthorizeCode setDescription(String description) {
        this.description = description == null ? null : description.trim();
        return this;
    }

    public String getCode() {
        return code;
    }

    public CommonAuthorizeCode setCode(String code) {
        this.code = code == null ? null : code.trim();
        return this;
    }

    public Integer getEnabled() {
        return enabled;
    }

    public CommonAuthorizeCode setEnabled(Integer enabled) {
        this.enabled = enabled;
        return this;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public CommonAuthorizeCode setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", code=").append(code);
        sb.append(", enabled=").append(enabled);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table common_authorize_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        name("name"),
        description("description"),
        code("code"),
        enabled("enabled"),
        deleted("deleted");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table common_authorize_code
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_authorize_code
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_authorize_code
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_authorize_code
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_authorize_code
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_authorize_code
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}