package com.github.misterchangray.dao.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="com.github.misterchangray.dao.entity.CommonFile")
public class CommonFile {
    @ApiModelProperty(value="id文件ID;这里使用UUID")
    private String id;

    @ApiModelProperty(value="fileName上传文件的名称")
    private String fileName;

    @ApiModelProperty(value="fileSize上传文件的大小")
    private String fileSize;

    @ApiModelProperty(value="fileSuffix上传文件的后缀")
    private String fileSuffix;

    @ApiModelProperty(value="fileMd5上传文件的MD5")
    private String fileMd5;

    @ApiModelProperty(value="fileType上传文件的类型")
    private String fileType;

    @ApiModelProperty(value="filePath上传文件保存位置")
    private String filePath;

    @ApiModelProperty(value="fileCompPath上传文件缩略图;图片才有")
    private String fileCompPath;

    @ApiModelProperty(value="tag上传文件标签")
    private String tag;

    @ApiModelProperty(value="deleted0false;1true")
    private Integer deleted;

    public String getId() {
        return id;
    }

    public CommonFile setId(String id) {
        this.id = id == null ? null : id.trim();
        return this;
    }

    public String getFileName() {
        return fileName;
    }

    public CommonFile setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
        return this;
    }

    public String getFileSize() {
        return fileSize;
    }

    public CommonFile setFileSize(String fileSize) {
        this.fileSize = fileSize == null ? null : fileSize.trim();
        return this;
    }

    public String getFileSuffix() {
        return fileSuffix;
    }

    public CommonFile setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix == null ? null : fileSuffix.trim();
        return this;
    }

    public String getFileMd5() {
        return fileMd5;
    }

    public CommonFile setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5 == null ? null : fileMd5.trim();
        return this;
    }

    public String getFileType() {
        return fileType;
    }

    public CommonFile setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
        return this;
    }

    public String getFilePath() {
        return filePath;
    }

    public CommonFile setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
        return this;
    }

    public String getFileCompPath() {
        return fileCompPath;
    }

    public CommonFile setFileCompPath(String fileCompPath) {
        this.fileCompPath = fileCompPath == null ? null : fileCompPath.trim();
        return this;
    }

    public String getTag() {
        return tag;
    }

    public CommonFile setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
        return this;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public CommonFile setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fileName=").append(fileName);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", fileSuffix=").append(fileSuffix);
        sb.append(", fileMd5=").append(fileMd5);
        sb.append(", fileType=").append(fileType);
        sb.append(", filePath=").append(filePath);
        sb.append(", fileCompPath=").append(fileCompPath);
        sb.append(", tag=").append(tag);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table common_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        fileName("file_name"),
        fileSize("file_size"),
        fileSuffix("file_suffix"),
        fileMd5("file_md5"),
        fileType("file_type"),
        filePath("file_path"),
        fileCompPath("file_comp_path"),
        tag("tag"),
        deleted("deleted");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table common_file
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_file
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_file
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_file
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_file
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table common_file
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}